# Generated by Django 3.0.7 on 2020-06-16 09:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0005_auto_20200616_0854'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='source',
            new_name='subcategory',
        ),
    ]
